apiVersion: v2
name: datahub
description: A Helm chart for LinkedIn DataHub
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: datahub-gms
    version: 0.2.9
    repository: file://./subcharts/datahub-gms
    condition: datahub-gms.enabled

  - name: datahub-frontend
    version: 0.2.9
    repository: file://./subcharts/datahub-frontend
    condition: datahub-frontend.enabled

  - name: datahub-mae-consumer
    version: 0.2.7
    repository: file://./subcharts/datahub-mae-consumer
    condition: global.datahub_standalone_consumers_enabled

  - name: datahub-mce-consumer
    version: 0.2.8
    repository: file://./subcharts/datahub-mce-consumer
    condition: global.datahub_standalone_consumers_enabled

  - name: datahub-ingestion-cron
    version: 0.2.5
    repository: file://./subcharts/datahub-ingestion-cron
    condition: datahub-ingestion-cron.enabled

maintainers:
  - name: DataMigrationTeam
